"""add prazo_entrega e recorrente a contratos

Revision ID: 0c68b5fb3396
Revises: 8b43ce22276b
Create Date: 2026-06-08 21:51:01.561970

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c68b5fb3396"
down_revision: str | Sequence[str] | None = "8b43ce22276b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contratos", sa.Column("prazo_entrega", sa.Date(), nullable=True))
    op.add_column(
        "contratos",
        sa.Column("recorrente", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contratos", "recorrente")
    op.drop_column("contratos", "prazo_entrega")
    # ### end Alembic commands ###
