"""models base (schema inicial)

Revision ID: 8213fa4c3b5f
Revises:
Create Date: 2026-06-04 22:10:27.207610

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8213fa4c3b5f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cargos",
        sa.Column("id_cargo", sa.Integer(), nullable=False),
        sa.Column("nome_cargo", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id_cargo"),
        sa.UniqueConstraint("nome_cargo"),
    )
    op.create_table(
        "empresas",
        sa.Column("id_empresa", sa.Integer(), nullable=False),
        sa.Column("razao_social", sa.String(length=255), nullable=False),
        sa.Column("nome_fantasia", sa.String(length=255), nullable=True),
        sa.Column("cnpj", sa.String(length=18), nullable=False),
        sa.Column("logradouro", sa.String(length=255), nullable=True),
        sa.Column("numero", sa.String(length=255), nullable=True),
        sa.Column("bairro", sa.String(length=255), nullable=True),
        sa.Column("cidade", sa.String(length=255), nullable=True),
        sa.Column("uf", sa.String(length=255), nullable=True),
        sa.Column("cep", sa.String(length=255), nullable=True),
        sa.Column("telefone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("representante_nome", sa.String(length=255), nullable=True),
        sa.Column("representante_cpf", sa.String(length=14), nullable=True),
        sa.Column("representante_contato", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id_empresa"),
        sa.UniqueConstraint("cnpj"),
    )
    op.create_table(
        "permissoes",
        sa.Column("id_permissao", sa.Integer(), nullable=False),
        sa.Column("descricao", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id_permissao"),
    )
    op.create_table(
        "servicos",
        sa.Column("id_servico", sa.Integer(), nullable=False),
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id_servico"),
        sa.UniqueConstraint("nome"),
    )
    op.create_table(
        "empresa_servico",
        sa.Column("id_empresa", sa.Integer(), nullable=False),
        sa.Column("id_servico", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["id_empresa"], ["empresas.id_empresa"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["id_servico"], ["servicos.id_servico"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id_empresa", "id_servico"),
    )
    op.create_table(
        "reunioes",
        sa.Column("id_reuniao", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=True),
        sa.Column("data", sa.Date(), nullable=True),
        sa.Column("hora", sa.Time(), nullable=True),
        sa.Column("presencial", sa.Boolean(), nullable=False),
        sa.Column("local", sa.String(length=255), nullable=True),
        sa.Column("pauta", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=255), server_default="agendada", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id_empresa"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id_reuniao"),
    )
    op.create_table(
        "usuarios",
        sa.Column("id_usuario", sa.Integer(), nullable=False),
        sa.Column("nome_completo", sa.String(length=255), nullable=False),
        sa.Column("cargo_id", sa.Integer(), nullable=False),
        sa.Column("cpf", sa.String(length=14), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("contato", sa.String(length=50), nullable=False),
        sa.Column("situacao", sa.String(length=255), server_default="ativo", nullable=False),
        sa.Column("senha_hash", sa.String(length=60), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["cargo_id"], ["cargos.id_cargo"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id_usuario"),
        sa.UniqueConstraint("cpf"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "documentos",
        sa.Column("id_documento", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("tipo_documento", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=True),
        sa.Column("validado", sa.String(length=255), server_default="pendente", nullable=False),
        sa.Column("analista_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["analista_id"], ["usuarios.id_usuario"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id_empresa"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id_documento"),
    )
    op.create_table(
        "notificacoes",
        sa.Column("id_notificacao", sa.Integer(), nullable=False),
        sa.Column("id_usuario", sa.Integer(), nullable=False),
        sa.Column("mensagem", sa.String(length=255), nullable=False),
        sa.Column("data_envio", sa.Date(), nullable=True),
        sa.Column("tipo", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["id_usuario"], ["usuarios.id_usuario"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id_notificacao"),
    )
    op.create_table(
        "participantes_reuniao",
        sa.Column("id_reuniao", sa.Integer(), nullable=False),
        sa.Column("id_usuario", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["id_reuniao"], ["reunioes.id_reuniao"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["id_usuario"], ["usuarios.id_usuario"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id_reuniao", "id_usuario"),
    )
    op.create_table(
        "propostas",
        sa.Column("id_proposta", sa.Integer(), nullable=False),
        sa.Column("empresa_id", sa.Integer(), nullable=False),
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=255), server_default="rascunho", nullable=False),
        sa.Column("data_criacao", sa.Date(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["empresa_id"], ["empresas.id_empresa"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["usuario_id"], ["usuarios.id_usuario"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id_proposta"),
    )
    op.create_table(
        "usuario_permissoes",
        sa.Column("id_usuario", sa.Integer(), nullable=False),
        sa.Column("id_permissao", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["id_permissao"], ["permissoes.id_permissao"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["id_usuario"], ["usuarios.id_usuario"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id_usuario", "id_permissao"),
    )
    op.create_table(
        "contratos",
        sa.Column("id_contrato", sa.Integer(), nullable=False),
        sa.Column("proposta_id", sa.Integer(), nullable=False),
        sa.Column("data_inicio", sa.Date(), nullable=True),
        sa.Column("data_fim", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=255), server_default="ativo", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["proposta_id"], ["propostas.id_proposta"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id_contrato"),
        sa.UniqueConstraint("proposta_id"),
    )
    op.create_table(
        "planilhas",
        sa.Column("id_planilha", sa.Integer(), nullable=False),
        sa.Column("contrato_id", sa.Integer(), nullable=False),
        sa.Column("url_google_sheets", sa.String(length=255), nullable=True),
        sa.Column("bloqueada", sa.Boolean(), nullable=False),
        sa.Column("permissao_visualizacao", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["contrato_id"], ["contratos.id_contrato"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id_planilha"),
    )
    op.create_table(
        "relatorios",
        sa.Column("id_relatorio", sa.Integer(), nullable=False),
        sa.Column("contrato_id", sa.Integer(), nullable=False),
        sa.Column("url_pdf", sa.String(length=255), nullable=True),
        sa.Column("data_envio", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["contrato_id"], ["contratos.id_contrato"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id_relatorio"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("relatorios")
    op.drop_table("planilhas")
    op.drop_table("contratos")
    op.drop_table("usuario_permissoes")
    op.drop_table("propostas")
    op.drop_table("participantes_reuniao")
    op.drop_table("notificacoes")
    op.drop_table("documentos")
    op.drop_table("usuarios")
    op.drop_table("reunioes")
    op.drop_table("empresa_servico")
    op.drop_table("servicos")
    op.drop_table("permissoes")
    op.drop_table("empresas")
    op.drop_table("cargos")
    # ### end Alembic commands ###
