"""add papel ao usuario

Revision ID: a6703fd1b5bf
Revises: 79cc1a5467c5
Create Date: 2026-06-05 00:08:24.134646

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6703fd1b5bf"
down_revision: str | Sequence[str] | None = "79cc1a5467c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "usuarios",
        sa.Column("papel", sa.String(length=255), server_default="analista", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("usuarios", "papel")
    # ### end Alembic commands ###
